# Generated by Django 2.2.4 on 2019-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='susurl',
            name='shortcode',
            field=models.CharField(default='sus', max_length=16),
        ),
    ]
