# Generated by Django 2.2.4 on 2019-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_susurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='susurl',
            name='shortcode',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
