# Generated by Django 2.2.4 on 2019-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190902_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='susurl',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='susurl',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='susurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
