# Generated by Django 2.2.4 on 2019-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20190902_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=16, unique=True)),
                ('ipaddr', models.CharField(max_length=12, unique=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, null=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='susurl',
            name='last_accessed',
        ),
    ]
