# Generated by Django 2.2.4 on 2019-09-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20190902_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipstore',
            old_name='hits',
            new_name='uhits',
        ),
    ]
