# Generated by Django 2.2.4 on 2019-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20190902_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipstore',
            name='ipaddr',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
