# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20181120_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
