# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20181128_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url]),
        ),
    ]
