# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-05 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20181204_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
