# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-02 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_shorten_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorten',
            name='hits',
        ),
    ]
